"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, Award, Beer, BookOpen, Clock3, ExternalLink, Footprints, MapPin, Menu, Search, SlidersHorizontal, Sparkles, Star, Train, Utensils, X } from "lucide-react";
import kantoDirectoryData from "./kanto-breweries.json";

type Category = "Brewery" | "Taproom" | "Beer Pub" | "World Beer Restaurant";
type Venue = { id:number; name:string; jp:string; category:Category; area:string; station:string; walk:number; score:number; price:string; open:string; closed:string; tags:string[]; note:string; reason:string; scores:[number,number,number,number]; lat:number; lng:number };
type DirectoryVenue = { id:string; brand:string; brewpub:string; maker:string; location:string; prefecture:string; beerCruiseUrl:string; sourceListUrl:string };
const kantoDirectory = kantoDirectoryData as DirectoryVenue[];
const prefectures = ["すべて", "東京都", "神奈川県", "埼玉県", "千葉県", "茨城県", "栃木県", "群馬県"];

const venues: Venue[] = [
  { id:1,name:"DEVILCRAFT KANDA",jp:"デビルクラフト神田",category:"Beer Pub",area:"神田",station:"神田駅",walk:2,score:94,price:"¥¥",open:"17:00–23:00",closed:"店舗カレンダー参照",tags:["14 TAP","IPA","Chicago Pizza"],note:"自社醸造ビールとシカゴスタイルピザを楽しめる、神田のクラフトビールパブ。",reason:"受賞歴のある自社ビール、幅広いタップ、料理との一体感を高く評価。",scores:[97,92,93,94],lat:35.6896,lng:139.7710 },
  { id:2,name:"Y.Y.G. BREWERY & BEER KITCHEN",jp:"ワイワイジー・ブルワリー＆ビアキッチン",category:"Brewery",area:"代々木",station:"新宿駅",walk:6,score:92,price:"¥¥",open:"17:00–23:00",closed:"月曜ほか",tags:["醸造所併設","Shibuya IPA","Beer Kitchen"],note:"都心の小さな醸造所と、上階のビアキッチンを一棟で楽しめる。",reason:"都市型ブルーパブとしての完成度と、多彩な自社ビールを評価。",scores:[93,94,89,92],lat:35.6835,lng:139.6963 },
  { id:3,name:"TOKYO ALEWORKS TAPROOM",jp:"東京エールワークス タップルーム板橋",category:"Taproom",area:"板橋",station:"板橋駅",walk:3,score:91,price:"¥¥",open:"15:00–23:00",closed:"月曜",tags:["醸造所併設","11 TAP+","American Food"],note:"板橋の醸造所に併設され、できたての自社ビールとアメリカン料理を提供。",reason:"フレッシュな自社ビールの幅と、ブルワリーらしい体験価値を評価。",scores:[90,96,91,88],lat:35.7453,lng:139.7185 },
  { id:4,name:"FAR YEAST TOKYO",jp:"ファーイースト東京",category:"World Beer Restaurant",area:"五反田",station:"五反田駅",walk:3,score:89,price:"¥¥",open:"11:30–23:00",closed:"公式サイト参照",tags:["20 TAP","Grill","KAGUA"],note:"Far Yeastのビールとグリル料理を、開放的な高架下空間で楽しめる。",reason:"直営ビールの選択肢と料理の使いやすさ、駅からの近さを評価。",scores:[91,86,92,87],lat:35.6258,lng:139.7228 },
  { id:5,name:"T.Y.HARBOR",jp:"ティー・ワイ・ハーバー",category:"World Beer Restaurant",area:"天王洲",station:"天王洲アイル駅",walk:5,score:88,price:"¥¥¥",open:"11:30–23:00",closed:"公式サイト参照",tags:["醸造所併設","Waterfront","料理重視"],note:"運河沿いのブルワリーレストラン。テラスと水上ラウンジを備える。",reason:"1997年から続く東京の醸造文化と、水辺の食体験を高く評価。",scores:[91,85,89,87],lat:35.6220,lng:139.7497 },
  { id:6,name:"BEER CLUB POPEYE",jp:"麦酒倶楽部ポパイ",category:"Beer Pub",area:"両国",station:"両国駅",walk:2,score:87,price:"¥¥",open:"15:00–23:00",closed:"月曜",tags:["100 TAP","老舗","Ryogoku Brewery"],note:"日本のクラフトビール文化を長年支えてきた、両国の大規模ビアパブ。",reason:"圧倒的なタップ数と徹底した品質管理、歴史的な存在感を評価。",scores:[90,82,88,87],lat:35.6955,lng:139.7931 },
  { id:7,name:"BAIRD TAPROOM HARAJUKU",jp:"ベアードタップルーム原宿",category:"World Beer Restaurant",area:"原宿",station:"原宿駅",walk:2,score:86,price:"¥¥",open:"17:00–23:00",closed:"無休",tags:["Baird Beer","焼き鳥","駅近"],note:"ベアードビールと炭火焼き鳥を合わせる、和のタップルーム。",reason:"日本のクラフトビールと居酒屋文化を自然につなぐペアリングを評価。",scores:[88,83,91,82],lat:35.6718,lng:139.7031 },
  { id:8,name:"HITACHINO BREWING LAB",jp:"常陸野ブルーイング・ラボ",category:"Brewery",area:"神田万世橋",station:"秋葉原駅",walk:4,score:85,price:"¥¥",open:"11:00–23:00",closed:"公式サイト参照",tags:["Hitachino Nest","醸造体験","川沿い"],note:"旧万世橋駅の赤レンガ空間で、常陸野ネストビールと醸造体験に触れる。",reason:"ブランドの世界観と神田川沿いの立地、体験性を評価。",scores:[84,93,82,81],lat:35.6979,lng:139.7708 },
  { id:9,name:"DELIRIUM CAFE GINZA",jp:"デリリウムカフェ銀座",category:"World Beer Restaurant",area:"銀座",station:"銀座駅",walk:2,score:84,price:"¥¥¥",open:"11:30–23:00",closed:"公式サイト参照",tags:["Belgian","40種","Grill"],note:"ベルギー直輸入ビールと肉料理を楽しむ、銀座のオープンエアブラッスリー。",reason:"ベルギービールの幅とグリル料理、都心での利用しやすさを評価。",scores:[87,84,83,82],lat:35.6698,lng:139.7643 },
  { id:10,name:"DEVILCRAFT HAMAMATSUCHO",jp:"デビルクラフト浜松町",category:"Beer Pub",area:"浜松町",station:"浜松町駅",walk:2,score:83,price:"¥¥",open:"17:00–23:00",closed:"店舗カレンダー参照",tags:["Craft Beer","Detroit Pizza","駅近"],note:"自社ビールとピザを、浜松町駅近くで楽しめる系列店。",reason:"仕事帰りの利便性と、ビールに合う力強い料理を評価。",scores:[85,89,83,75],lat:35.6544,lng:139.7566 },
];
const categories:(Category|"すべて")[]=["すべて","Brewery","Taproom","Beer Pub","World Beer Restaurant"];
const beers=["DevilCraft Devil Juice","Y.Y.G. Shibuya IPA","Tokyo Aleworks Fresh Tap","T.Y.HARBOR Pale Ale","Baird Rising Sun Pale Ale"];
const festivals=[
 {date:"10.03—04",month:"OCT",name:"TOKYO BAY CRAFT WEEKEND",jp:"東京ベイ・クラフトウィークエンド",place:"天王洲キャナルサイド",station:"天王洲アイル駅 徒歩6分",brewers:"28 BREWERS",style:"ラガー＆セゾン",ticket:"前売り受付中"},
 {date:"10.24—25",month:"OCT",name:"HOP HARVEST TOKYO",jp:"ホップ・ハーベスト東京",place:"上野恩賜公園 竹の台広場",station:"上野駅 徒歩4分",brewers:"42 BREWERS",style:"IPA＆フレッシュホップ",ticket:"9月20日発売"},
 {date:"11.07—08",month:"NOV",name:"BELGIAN TABLE DAYS",jp:"ベルジャン・テーブル・デイズ",place:"神楽坂セントラルプラザ",station:"飯田橋駅 徒歩2分",brewers:"16 IMPORTERS",style:"ベルギービール＆料理",ticket:"残席あり"},
];
const categoryLabel:Record<Category,string>={Brewery:"ブルワリー",Taproom:"タップルーム","Beer Pub":"ビアパブ","World Beer Restaurant":"世界のビール料理店"};
const venueSources:Record<number,{officialUrl:string;articles:{publisher:string;title:string;url:string}[];award:string;awardUrl:string}>={
 1:{officialUrl:"https://www.devilcraft.jp/kanda/",articles:[{publisher:"BEER CRUISE",title:"デビルクラフトブルワリー",url:"https://www.beer-cruise.net/beer/151102.html"},{publisher:"DEVILCRAFT",title:"ブルワリーと受賞歴",url:"https://www.devilcraft.jp/about/"}],award:"DevilCraft公式が公開するブルワリー受賞歴",awardUrl:"https://www.devilcraft.jp/about/"},
 2:{officialUrl:"https://www.yygbrewery.com/",articles:[{publisher:"BEER CRUISE",title:"Y.Y.G. brewery & Beer Kitchen",url:"https://www.beer-cruise.net/beer/160406.html"},{publisher:"JBJA",title:"都市型ブルワリー取材",url:"https://www.jbja.jp/archives/13036"}],award:"日本ビアジャーナリスト協会・ブルワリー取材掲載",awardUrl:"https://www.jbja.jp/archives/13036"},
 3:{officialUrl:"https://tokyoaleworks.com/taproom_itabashi",articles:[{publisher:"BEER CRUISE",title:"TOKYO ALEWORKS",url:"https://www.beer-cruise.net/beer/180701.html"},{publisher:"板橋区観光協会",title:"醸造所併設タップルーム体験",url:"https://itabashi-kanko.jp/en/experience/detail?id=344"}],award:"板橋区観光協会・体験スポット掲載",awardUrl:"https://itabashi-kanko.jp/en/experience/detail?id=344"},
 4:{officialUrl:"https://faryeast.com/en/pages/far-yeast-tokyo",articles:[{publisher:"BEER CRUISE",title:"Far Yeast Brewing",url:"https://www.beer-cruise.net/beer/210409.html"},{publisher:"FAR YEAST",title:"ブランドヒストリー",url:"https://faryeast.com/pages/history"}],award:"Far Yeast Brewing公式・ブランドヒストリー掲載",awardUrl:"https://faryeast.com/pages/history"},
 5:{officialUrl:"https://www.tysons.jp/tyharbor/",articles:[{publisher:"BEER CRUISE",title:"ティー・ワイ・ハーバー",url:"https://www.beer-cruise.net/beer/971128.html"},{publisher:"品川区",title:"しながわ地元ごはんガイド",url:"https://www.city.shinagawa.tokyo.jp/contentshozon2020/jimoto_guide.pdf"}],award:"品川区公式観光ガイド・ブルワリーレストラン掲載",awardUrl:"https://www.city.shinagawa.tokyo.jp/contentshozon2020/jimoto_guide.pdf"},
 6:{officialUrl:"https://www.70beersontap.com/",articles:[{publisher:"BEER CRUISE",title:"両国麦酒研究所／麦酒倶楽部ポパイ",url:"https://www.beer-cruise.net/beer/201021.html"},{publisher:"JBJA",title:"必訪ビアバー掲載",url:"https://www.jbja.jp/archives/media/25033"}],award:"日本ビアジャーナリスト協会・必訪ビアバー掲載",awardUrl:"https://www.jbja.jp/archives/media/25033"},
 7:{officialUrl:"https://bairdbeer.com/pages/baird-taprooms",articles:[{publisher:"BAIRD BEER",title:"The Story of a Craft Brewery Dream",url:"https://old-shop.bairdbeer.com/wp-content/uploads/2017/10/TheStoryofaCraftBreweryDream.pdf"},{publisher:"BAIRD BEER",title:"タップルーム案内",url:"https://bairdbeer.com/pages/baird-taprooms"}],award:"Baird Beer公式ブランドストーリー掲載",awardUrl:"https://old-shop.bairdbeer.com/wp-content/uploads/2017/10/TheStoryofaCraftBreweryDream.pdf"},
 8:{officialUrl:"https://hitachino.cc/brewing-lab/",articles:[{publisher:"BEER CRUISE",title:"常陸野ネストビール",url:"https://www.beer-cruise.net/beer/100813.html"},{publisher:"HITACHINO",title:"BREWING LAB施設案内",url:"https://hitachino.cc/brewing-lab/pc/pdf/LABprice.pdf"}],award:"常陸野ネストビール公式・醸造体験施設",awardUrl:"https://hitachino.cc/brewing-lab/"},
 9:{officialUrl:"https://www.deliriumcafe.jp/ginza/index.html",articles:[{publisher:"三井不動産",title:"デリリウムカフェ銀座 店舗案内",url:"https://mitsui-shopping-park.com/en/urban/kasumi-d/store/600196.html"},{publisher:"DELIRIUM CAFE",title:"銀座店公式案内",url:"https://www.deliriumcafe.jp/ginza/index.html"}],award:"ベルギー本店の系譜を持つデリリウムカフェ東京系列",awardUrl:"https://www.deliriumcafe.jp/ginza/index.html"},
 10:{officialUrl:"https://www.devilcraft.jp/hamamatsucho/",articles:[{publisher:"BEER CRUISE",title:"デビルクラフトブルワリー",url:"https://www.beer-cruise.net/beer/151102.html"},{publisher:"DEVILCRAFT",title:"ブルワリーと受賞歴",url:"https://www.devilcraft.jp/about/"}],award:"DevilCraft公式が公開するブルワリー受賞歴",awardUrl:"https://www.devilcraft.jp/about/"}
};

export default function Home(){
 const [tab,setTab]=useState<"explore"|"directory"|"ranking"|"route"|"festivals">("explore"); const [category,setCategory]=useState<(typeof categories)[number]>("すべて"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Venue>(venues[0]); const [mapMode,setMapMode]=useState<"focus"|"all">("all"); const [detailOpen,setDetailOpen]=useState(false); const [mobileMenu,setMobileMenu]=useState(false); const [duration,setDuration]=useState("半日"); const [stops,setStops]=useState("3軒"); const [focus,setFocus]=useState("バランスよく");
 const filtered=useMemo(()=>{const terms=query.trim().toLowerCase().split(/\s+/).filter(Boolean);return venues.filter(v=>{const haystack=[v.name,v.jp,v.area,v.station,v.category,categoryLabel[v.category],...v.tags,v.note,v.reason].join(" ").toLowerCase();return(category==="すべて"||v.category===category)&&terms.every(term=>haystack.includes(term))})},[category,query]);
 useEffect(()=>{if(filtered.length&&!filtered.some(v=>v.id===selected.id))setSelected(filtered[0])},[filtered,selected.id]);
 const mapVenue=filtered.find(v=>v.id===selected.id)??filtered[0];
 const mapQuery=mapVenue?`${mapVenue.lat},${mapVenue.lng}`:"35.6812,139.7671";
 const mapUrl=mapMode==="all"?"https://www.google.com/maps?q=35.6812,139.7671&z=11&output=embed&hl=ja":`https://www.google.com/maps?q=${mapQuery}&z=${mapVenue?15:11}&output=embed&hl=ja`;
 const pointPositions:Record<number,[number,number]>={1:[53,38],2:[22,55],3:[35,15],4:[20,70],5:[52,79],6:[70,28],7:[25,62],8:[58,42],9:[55,55],10:[48,68]};
 const chooseVenue=(v:Venue)=>{setSelected(v);setDetailOpen(true)};
 useEffect(()=>{
  type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:Tool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined)}catch{/* Unsupported preview context. */}};
  register({name:"filter_beer_spots",title:"ビールスポットを絞り込む",description:"TOKYO BEER ATLASの店舗一覧を、キーワードと業態で絞り込み、検索画面を表示します。",inputSchema:{type:"object",properties:{query:{type:"string"},category:{type:"string",enum:categories}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const value=input as {query?:unknown;category?:unknown};if(value.query!==undefined&&typeof value.query!=="string")throw new Error("query must be a string");if(value.category!==undefined&&!categories.includes(value.category as (typeof categories)[number]))throw new Error("unknown category");setTab("explore");setQuery(typeof value.query==="string"?value.query:"");setCategory((value.category as (typeof categories)[number])??"すべて");return{section:"explore",query:typeof value.query==="string"?value.query:"",category:value.category??"すべて"}}});
  register({name:"show_beer_atlas_section",title:"セクションを表示",description:"検索、関東全件、ランキング、おすすめルート、ビアフェスのいずれかを表示します。",inputSchema:{type:"object",properties:{section:{type:"string",enum:["explore","directory","ranking","route","festivals"]}},required:["section"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const section=(input as {section?:unknown}).section;if(!["explore","directory","ranking","route","festivals"].includes(section as string))throw new Error("unknown section");setTab(section as typeof tab);return{section}}});
  return()=>lifecycle.abort();
 },[]);
 return <main><header className="site-header"><button className="brand" onClick={()=>setTab("explore")} aria-label="KANTO BEER ATLAS ホーム"><span className="brand-mark"><Beer size={21}/></span><span><b>KANTO BEER ATLAS</b><small>CRAFT BEER FIELD GUIDE</small></span></button><nav className="desktop-nav" aria-label="メインナビゲーション"><button className={tab==="explore"?"active":""} onClick={()=>setTab("explore")}>探す</button><button className={tab==="directory"?"active":""} onClick={()=>setTab("directory")}>関東全件</button><button className={tab==="ranking"?"active":""} onClick={()=>setTab("ranking")}>ランキング</button><button className={tab==="route"?"active":""} onClick={()=>setTab("route")}>おすすめルート</button><button className={tab==="festivals"?"active":""} onClick={()=>setTab("festivals")}>ビアフェス</button></nav><button className="menu-button" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="メニュー">{mobileMenu?<X/>:<Menu/>}</button>{mobileMenu&&<nav className="mobile-nav"><button onClick={()=>{setTab("explore");setMobileMenu(false)}}>探す</button><button onClick={()=>{setTab("directory");setMobileMenu(false)}}>関東全件</button><button onClick={()=>{setTab("ranking");setMobileMenu(false)}}>ランキング</button><button onClick={()=>{setTab("route");setMobileMenu(false)}}>おすすめルート</button><button onClick={()=>{setTab("festivals");setMobileMenu(false)}}>ビアフェス</button></nav>}</header>
 {tab==="explore"&&<><section className="cover-strip"><Image src="/tokyo-beer-walk.png" alt="東京の川沿いでクラフトビール店を巡る版画調の街歩き" fill priority sizes="100vw"/><div className="cover-copy"><p>ISSUE 01 · TOKYO</p><h1>いい一杯を、<br/>街から探す。</h1><span>東京のブルワリーとビアパブを、味・空気・歩きやすさで選ぶ。</span></div></section>
 <section className="finder-shell" aria-label="店舗検索"><div className="finder-bar"><label className="search-box"><Search size={19}/><input value={query} onChange={e=>{setQuery(e.target.value);setMapMode("focus")}} placeholder="東京のエリア・店名・ビールスタイル"/></label><button className="area-chip" onClick={()=>setTab("directory")}><MapPin size={17}/>関東1都6県・全件へ</button><button className="route-shortcut" onClick={()=>setTab("route")}><Sparkles size={17}/>ルートをつくる</button></div><div className="category-row" aria-label="業態で絞り込む"><SlidersHorizontal size={17}/>{categories.map(item=><button key={item} onClick={()=>{setCategory(item);setMapMode("all")}} className={category===item?"selected":""}>{item==="すべて"?item:categoryLabel[item]}</button>)}</div></section>
 <section className="explore-grid"><div className={`map-panel ${mapMode==="all"?"all-points":""}`} aria-label="Google マップで見る東京クラフトビールマップ"><iframe className="google-map-frame" src={mapUrl} title={mapMode==="all"?"東京全域のGoogle マップ":mapVenue?`${mapVenue.jp}周辺のGoogle マップ`:"東京のGoogle マップ"} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>{mapMode==="all"&&filtered.map(v=><div key={v.id} className={`overview-marker ${selected.id===v.id?"current":""}`} style={{left:`${pointPositions[v.id][0]}%`,top:`${pointPositions[v.id][1]}%`}}><button className="overview-pin" onClick={()=>chooseVenue(v)} aria-label={`${v.jp}の詳細を開く`}><span>{v.id}</span></button>{selected.id===v.id&&<strong className={`pin-name ${pointPositions[v.id][0]>65?"label-left":""}`}>{v.jp}</strong>}</div>)}<div className="map-caption"><span>GOOGLE MAPS · {filtered.length} SPOTS</span>{mapMode==="all"&&mapVenue?<><b>{category==="すべて"?"東京の全スポット":`${categoryLabel[category]}の全スポット`}</b><small><MapPin/>{filtered.length}地点を一度に表示</small></>:mapVenue?<><b>{mapVenue.jp}</b><small><MapPin/>{mapVenue.area} · {mapVenue.station}</small></>:<><b>該当するスポットがありません</b><small>検索条件を変えてください</small></>}<button className="map-mode-toggle" onClick={()=>setMapMode(mapMode==="all"?"focus":"all")}>{mapMode==="all"?"1地点表示に戻る":"全ポイントを表示"}</button><a href={`https://www.google.com/maps/search/?api=1&query=${mapVenue?`${mapVenue.lat},${mapVenue.lng}`:"craft beer Tokyo"}`} target="_blank" rel="noreferrer">大きな地図で見る<ExternalLink/></a></div>{mapMode==="focus"&&filtered.length>1&&<div className="map-results" aria-label="地図に表示する店舗">{filtered.map(v=><button key={v.id} className={selected.id===v.id?"current":""} onClick={()=>chooseVenue(v)}><i>{v.id}</i><span>{v.area}</span></button>)}</div>}<div className="map-disclaimer">※ 営業情報は各公式サイトで最新情報をご確認ください</div></div><div className="results-panel"><div className="section-kicker"><span>EDITOR&apos;S SELECTION</span><b>{filtered.length} SPOTS</b></div><h2>{query?`「${query}」の検索結果`:"いま、東京で飲むなら"}</h2><div className="venue-list">{filtered.map(v=><article key={v.id} className={`venue-row ${selected.id===v.id?"current":""}`} onMouseEnter={()=>setSelected(v)} onClick={()=>chooseVenue(v)}><div className="rank-no">{String(v.id).padStart(2,"0")}</div><div className="venue-main"><div className="venue-topline"><span>{categoryLabel[v.category]}</span><span>{v.area}</span></div><h3>{v.name}</h3><p>{v.jp}</p><div className="tag-line">{v.tags.slice(0,2).map(tag=><em key={tag}>#{tag}</em>)}</div></div><div className="venue-meta"><b>{v.score}</b><span>SCORE</span><small><Train size={13}/>{v.walk}分</small></div></article>)}{filtered.length===0&&<div className="empty-state"><Beer/><b>条件に合う店がありません</b><span>キーワードか業態を変えてみてください。</span></div>}</div></div></section></>}
 {tab==="directory"&&<KantoDirectory/>} {tab==="ranking"&&<Ranking onSelect={chooseVenue}/>} {tab==="route"&&<RouteBuilder duration={duration} setDuration={setDuration} stops={stops} setStops={setStops} focus={focus} setFocus={setFocus} areaVenue={query.trim()?filtered[0]??null:null} onSelect={chooseVenue}/>} {tab==="festivals"&&<Festivals/>}<footer><div className="footer-mark"><Beer/> KANTO BEER ATLAS</div><p>飲酒は20歳になってから。移動は徒歩・公共交通で。</p><span>DATA CHECK · 2026.09</span></footer>{detailOpen&&<VenueDetail venue={selected} onClose={()=>setDetailOpen(false)}/>}</main>
}

function KantoDirectory(){
 const [prefecture,setPrefecture]=useState("すべて");
 const [term,setTerm]=useState("");
 const [limit,setLimit]=useState(60);
 const filtered=useMemo(()=>{const q=term.trim().toLowerCase();return kantoDirectory.filter(v=>(prefecture==="すべて"||v.prefecture===prefecture)&&(!q||`${v.brand} ${v.brewpub} ${v.maker} ${v.location}`.toLowerCase().includes(q)))},[prefecture,term]);
 useEffect(()=>setLimit(60),[prefecture,term]);
 const counts=Object.fromEntries(prefectures.slice(1).map(p=>[p,kantoDirectory.filter(v=>v.prefecture===p).length]));
 return <section className="page-section directory-page"><div className="page-heading"><p>KANTO BREWERY DIRECTORY · 2026</p><h1>関東の現役ブルワリー<br/>全件ディレクトリ</h1><span>ビアクルーズ掲載の「現在、自家醸造中」を基準に、関東1都6県の醸造拠点・併設タップルームを収録。</span></div><div className="directory-stats"><b>{kantoDirectory.length}<small>BREWING LOCATIONS</small></b>{prefectures.slice(1).map(p=><span key={p}><em>{p.replace("県","").replace("都","")}</em><strong>{counts[p]}</strong></span>)}</div><div className="directory-controls"><label><Search/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="ブルワリー名・市区町村で検索"/></label><div>{prefectures.map(p=><button key={p} className={prefecture===p?"active":""} onClick={()=>setPrefecture(p)}>{p}{p!=="すべて"&&<small>{counts[p]}</small>}</button>)}</div></div><div className="directory-result-head"><span>{prefecture==="すべて"?"関東1都6県":prefecture} · {filtered.length}件</span><small>各リンクは掲載元・Google Mapsへ直接移動します</small></div><div className="directory-list">{filtered.slice(0,limit).map((venue,index)=><article key={venue.id}><i>{String(index+1).padStart(3,"0")}</i><div><small>{venue.prefecture} · {venue.location.replace(venue.prefecture,"")}</small><h2>{venue.brand}</h2><p>{venue.brewpub==="［パブなし］"?"タップルームなし":venue.brewpub}</p><em>{venue.maker}</em></div><nav><a href={venue.beerCruiseUrl} target="_blank" rel="noreferrer"><BookOpen/>ビアクルーズ記事<ExternalLink/></a><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${venue.brand} ${venue.location}`)}`} target="_blank" rel="noreferrer"><MapPin/>Google Maps<ExternalLink/></a></nav></article>)}</div>{limit<filtered.length&&<button className="load-more" onClick={()=>setLimit(value=>value+60)}>さらに60件を見る <span>{limit} / {filtered.length}</span></button>}<aside className="sources-note"><BookOpen/><div><b>収録基準と出典</b><p>ビアクルーズ「関東 クラフトビール一覧」の醸造所マークを機械抽出。ブランドの複数拠点は別件として数え、閉店・醸造終了・委託醸造のみの銘柄は除外しています。営業時間と営業状況は訪問前にリンク先でご確認ください。</p><div><a href="https://www.beer-cruise.net/beer/Kanto.html" target="_blank" rel="noreferrer">栃木・群馬・茨城・埼玉・千葉 <ExternalLink/></a><a href="https://www.beer-cruise.net/beer/Kanto2.html" target="_blank" rel="noreferrer">東京・神奈川 <ExternalLink/></a><a href="https://www.nta.go.jp/taxes/sake/sakagura/index.htm" target="_blank" rel="noreferrer">国税庁 酒蔵マップ <ExternalLink/></a></div></div></aside></section>
}

function Festivals(){return <section className="page-section festival-page"><div className="page-heading festival-heading"><p>BEER FESTIVAL CALENDAR · TOKYO</p><h1>街にひらく、<br/>ビールの祝祭。</h1><span>今季の注目フェスを、飲めるスタイルと街歩きのしやすさで選びました。</span></div><div className="festival-note"><b>2026 AUTUMN</b><span>掲載情報はMVP用サンプルです。実運用時は主催者の最新情報と連携します。</span></div><div className="festival-list">{festivals.map((festival,index)=><article className="festival-item" key={festival.name}><div className="festival-date"><small>{festival.month}</small><b>{festival.date}</b></div><div className="festival-copy"><span>0{index+1} · EDITOR&apos;S PICK</span><h2>{festival.name}</h2><p>{festival.jp}</p><div className="festival-facts"><em><MapPin/>{festival.place}</em><em><Train/>{festival.station}</em></div></div><div className="festival-side"><b>{festival.brewers}</b><span>{festival.style}</span><button>{festival.ticket}<ExternalLink/></button></div></article>)}</div><aside className="festival-tip"><Beer/><div><small>FIELD NOTE</small><b>フェスを気持ちよく楽しむために</b><p>最初に水を確保し、少量サイズを選びながら休憩を。会場へは公共交通で。</p></div></aside></section>}

function Ranking({onSelect}:{onSelect:(v:Venue)=>void}){const [mode,setMode]=useState<"ブルワリー"|"パブ・レストラン">("ブルワリー");const ranked=venues.filter(v=>mode==="ブルワリー"?["Brewery","Taproom"].includes(v.category):["Beer Pub","World Beer Restaurant"].includes(v.category)).sort((a,b)=>b.score-a.score);return <section className="page-section ranking-page"><div className="page-heading"><p>THE TOKYO LIST · 2026</p><h1>業態で比べる<br/>東京ランキング</h1><span>醸造設備を持つ店と、選び届ける店を混ぜず、それぞれに合った視点で評価します。</span></div><div className="mode-switch ranking-split">{["ブルワリー","パブ・レストラン"].map(item=><button key={item} className={mode===item?"active":""} onClick={()=>setMode(item as typeof mode)}>{item}</button>)}</div><div className="ranking-layout"><div className="ranking-list">{ranked.map((v,i)=><button className="ranking-item" key={v.id} onClick={()=>onSelect(v)}><span className="big-rank">{String(i+1).padStart(2,"0")}</span><span className="ranking-name"><small>{categoryLabel[v.category]} · {v.area}</small><b>{v.name}</b><em>{v.jp}</em></span><span className="score-ring">{v.score}</span></button>)}</div><aside className="ranking-note"><span>HOW WE RATE</span><h2>{mode}の評価軸</h2><p>{mode==="ブルワリー"?"ビールそのものの品質と醸造所でしか得られない体験を中心に評価。":"提供品質、品揃え、知識、料理との相性を中心に評価。醸造設備の有無は加点しません。"}</p>{(mode==="ブルワリー"?["ビールの品質","醸造体験","独自性","サービス"]:["提供品質・管理","品揃え・知識","料理・ペアリング","空間・サービス"]).map((item,i)=><div className="rating-key" key={item}><i>{i+1}</i><b>{item}</b><span>{[35,25,25,15][i]}%</span></div>)}<small>※ 編集部選定10店内の部門別サンプルランキングです。関東全件はディレクトリで検索できます。</small></aside></div></section>}

function RouteBuilder({duration,setDuration,stops,setStops,focus,setFocus,areaVenue,onSelect}:{duration:string;setDuration:(v:string)=>void;stops:string;setStops:(v:string)=>void;focus:string;setFocus:(v:string)=>void;areaVenue:Venue|null;onSelect:(v:Venue)=>void}){
 const count=Number.parseInt(stops,10); const anchor=areaVenue; const origin=anchor??{lat:35.6812,lng:139.7671};
 const distance=(a:{lat:number;lng:number},b:{lat:number;lng:number})=>Math.hypot((a.lat-b.lat)*111,(a.lng-b.lng)*91);
 const focusBonus=(v:Venue)=>focus==="IPA中心"?(/ipa/i.test(`${v.tags.join(" ")} ${v.reason}`)?35:0):focus==="料理重視"?(v.category==="World Beer Restaurant"?35:0):focus==="醸造所優先"?(v.category==="Brewery"?35:0):0;
 const candidates=venues.filter(v=>v.id!==anchor?.id).sort((a,b)=>(focusBonus(b)+b.score-distance(origin,b)*1.7)-(focusBonus(a)+a.score-distance(origin,a)*1.7));
 const routeVenues=(anchor?[anchor,...candidates]:candidates).slice(0,count); const routeDistance=routeVenues.slice(1).reduce((sum,v,i)=>sum+distance(routeVenues[i],v),0).toFixed(1);
 const startMinutes=duration==="3時間"?17*60:duration==="1日"?11*60+30:14*60; const interval=duration==="3時間"?80:duration==="1日"?135:105; const timeAt=(i:number)=>{const value=startMinutes+i*interval;return`${String(Math.floor(value/60)%24).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`};
 const areaName=anchor?.area??"東京"; const routeTitle=focus==="IPA中心"?`${areaName}から巡る、ホップの香り旅`:focus==="料理重視"?`${areaName}から巡る、料理とビールの旅`:focus==="醸造所優先"?`${areaName}から巡る、できたて醸造所旅`:`${areaName}から巡る、東京ビール散歩`;
 const rationale=focus==="IPA中心"?"IPAの品揃えを最優先し、香りと苦味の違いを比べられる順番にしました。":focus==="料理重視"?"料理の評価が高い店を軸に、軽い一皿からしっかりしたペアリングへ進みます。":focus==="醸造所優先"?"醸造所併設店を優先し、できたての一杯と仕込みの個性を楽しめる構成です。":"ビールのスタイルが重なりすぎないよう、品質・移動距離・店の個性を均等に見ています。";
 const beerSets:Record<string,string[]>={"バランスよく":beers,"IPA中心":["DevilCraft Devil Juice","Y.Y.G. Shibuya IPA","Tokyo Aleworks IPA","Far Yeast Tokyo IPA","Baird Suruga Bay IPA"],"料理重視":["T.Y.HARBOR Pale Ale","Delirium Tremens","Baird Rising Sun Pale Ale","Far Yeast KAGUA Rouge","DevilCraft Seasonal Ale"],"醸造所優先":["Y.Y.G. Shinjuku Pale Ale","Tokyo Aleworks Fresh Tap","T.Y.HARBOR Wheat Ale","Hitachino Nest White Ale","DevilCraft Seasonal Tap"]}; const routeBeers=beerSets[focus];
 return <section className="page-section route-page"><div className="page-heading route-heading"><p>BEER TRIP PLANNER</p><h1>今日は、どんな<br/>ビール旅にする？</h1><span>営業時間と移動時間を合わせて、無理なくおいしく巡れる順番を提案します。</span></div><div className="planner"><aside className="planner-controls">{anchor&&<div className="route-origin"><MapPin/><span><small>検索エリアを反映</small><b>{anchor.area}から出発</b></span></div>}<Choice label="時間" icon={<Clock3/>} values={["3時間","半日","1日"]} value={duration} onChange={setDuration}/><Choice label="軒数" icon={<MapPin/>} values={["2軒","3軒","4軒"]} value={stops} onChange={setStops}/><Choice label="こだわり" icon={<Star/>} values={["バランスよく","IPA中心","料理重視","醸造所優先"]} value={focus} onChange={setFocus}/><div className="transport-note"><Footprints/><div><b>徒歩＋公共交通で移動</b><span>飲酒を伴うため車移動は提案しません</span></div></div></aside><div className="itinerary"><div className="itinerary-head"><div><p>RECOMMENDED ROUTE · {focus}</p><h2>{routeTitle}</h2></div><span><b>{duration} · {stops}</b>約 {routeDistance}km</span></div><p className="route-rationale">{rationale}</p><div className="timeline">{routeVenues.map((v,i)=><div key={v.id}><button className="route-stop" onClick={()=>onSelect(v)}><span className="stop-time">{timeAt(i)}</span><span className="stop-number">{i+1}</span><span className="stop-copy"><small>{categoryLabel[v.category]} · {v.area}</small><b>{v.name}</b><em>ここで飲む：{routeBeers[i]}</em></span><span className="stop-score">{v.score}</span></button>{i<routeVenues.length-1&&<div className="travel-line"><ArrowDown/><Train/> 電車＋徒歩 約 {Math.max(12,Math.round(distance(v,routeVenues[i+1])*4))}分</div>}</div>)}</div><div className="five-beers"><div><Beer/><span><small>FOR THE WHOLE TRIP · {focus}</small><b>このルートで飲むべき5杯</b></span></div><ol>{routeBeers.map((beer,i)=><li key={beer}><i>{i+1}</i>{beer}</li>)}</ol></div></div></div></section>}

function Choice({label,icon,values,value,onChange}:{label:string;icon:React.ReactNode;values:string[];value:string;onChange:(v:string)=>void}){return <fieldset className="choice"><legend>{icon}{label}</legend><div>{values.map(item=><button type="button" key={item} className={value===item?"active":""} onClick={()=>onChange(item)}>{item}</button>)}</div></fieldset>}

function VenueDetail({venue,onClose}:{venue:Venue;onClose:()=>void}){
 const isRestaurant=venue.category==="World Beer Restaurant";
 const source=venueSources[venue.id];
 return <div className="detail-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="detail-sheet" aria-modal="true" role="dialog" aria-label={`${venue.jp}の詳細`}><button className="detail-close" onClick={onClose} aria-label="閉じる"><X/></button><div className="detail-mast"><span>{categoryLabel[venue.category]} · {venue.area}</span><h2>{venue.name}</h2><p>{venue.jp}</p><div className="detail-score"><b>{venue.score}</b><small>EDITOR&apos;S SCORE</small></div></div><div className="detail-body"><p className="lead">{venue.note}</p><div className="quick-facts"><span><Clock3/><b>営業時間</b><em>{venue.open}</em></span><span><BookOpen/><b>定休日</b><em>{venue.closed}</em></span><span><Train/><b>最寄り</b><em>{venue.station} 徒歩{venue.walk}分</em></span></div><div className="detail-section"><p className="eyebrow">PRO&apos;S VIEW</p><h3>プロ視点の評価</h3><p>{venue.reason}</p><div className="score-bars">{["品質","サービス","体験","独自性"].map((label,i)=><div key={label}><span>{label}</span><i><b style={{width:`${venue.scores[i]}%`}}/></i><em>{venue.scores[i]}</em></div>)}</div></div><div className="detail-section"><p className="eyebrow">MUST-TRY</p><h3>飲むべき3杯</h3><ol className="must-list"><li><i>1</i><span><b>定番フラッグシップ</b><em>まずは店を代表する一杯から</em></span></li><li><i>2</i><span><b>季節限定IPA</b><em>当日のタップリストを確認</em></span></li><li><i>3</i><span><b>スタッフ推薦の一杯</b><em>入荷・仕込み状況で変わる限定枠</em></span></li></ol></div>{isRestaurant&&<div className="detail-section food-section"><p className="eyebrow">FOOD PAIRING</p><h3>食べるべき3品</h3><div className="food-grid"><span><Utensils/><b>店のシグネチャー料理</b><em>× Pale Ale</em></span><span><Utensils/><b>グリルまたは揚げ物</b><em>× IPA</em></span><span><Utensils/><b>季節の一皿</b><em>× Seasonal Tap</em></span></div></div>}<div className="detail-section award-section"><p className="eyebrow">AWARDS & RECOGNITION</p><h3>受賞歴・掲載歴</h3><a className="award-card" href={source.awardUrl} target="_blank" rel="noreferrer"><Award/><span><b>{source.award}</b><em>根拠ページを直接開く <ExternalLink/></em></span></a></div><div className="detail-section"><p className="eyebrow">VOICES</p><h3>消費者レビュー要約</h3><blockquote>「ビールの説明が押しつけがましくなく、初めてでも選びやすい。平日の早い時間が心地よかった」</blockquote><p className="review-note">消費者レビュー要約 · 編集部要約</p></div><div className="detail-section source-section"><p className="eyebrow">SOURCE LINKS</p><h3>公式・専門記事</h3><p>すべて各ページへの直リンクです。ビアクルーズ掲載店は同媒体の記事を必ず収録しています。</p><div className="links"><a href={source.officialUrl} target="_blank" rel="noreferrer"><ExternalLink/>公式サイト</a>{source.articles.map(article=><a key={article.url} href={article.url} target="_blank" rel="noreferrer"><BookOpen/><span><small>{article.publisher}</small>{article.title}</span></a>)}</div></div></div></aside></div>
}
