"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, Award, Beer, BookOpen, Clock3, ExternalLink, Footprints, MapPin, Menu, Search, SlidersHorizontal, Sparkles, Star, Train, Utensils, X } from "lucide-react";

type Category = "Brewery" | "Taproom" | "Beer Pub" | "World Beer Restaurant";
type Venue = { id:number; name:string; jp:string; category:Category; area:string; station:string; walk:number; score:number; price:string; open:string; closed:string; tags:string[]; note:string; reason:string; scores:[number,number,number,number]; lat:number; lng:number };

const venues: Venue[] = [
  { id:1,name:"KANDA FERMENT WORKS",jp:"神田ファーメント・ワークス",category:"Brewery",area:"神田",station:"神田駅",walk:5,score:94,price:"¥¥",open:"15:00–22:30",closed:"月曜",tags:["醸造所併設","Saison","限定醸造"],note:"小さな醸造室を眺めながら、食事に寄り添う季節のビールを。",reason:"醸造の独自性とタップの鮮度が抜群。スタッフの説明も簡潔で深い。",scores:[97,92,93,94],lat:35.6917,lng:139.7709 },
  { id:2,name:"RIVERBANK TAP KURAMAE",jp:"リバーバンク・タップ蔵前",category:"Taproom",area:"蔵前",station:"蔵前駅",walk:3,score:92,price:"¥¥",open:"12:00–22:00",closed:"火曜",tags:["川沿い","IPA","12 TAP"],note:"隅田川散歩の途中に立ち寄れる、明るいタップルーム。",reason:"国内外のIPA選定が明快。ロケーションと昼飲み体験も高評価。",scores:[93,94,89,92],lat:35.7039,lng:139.7908 },
  { id:3,name:"BRUSSELS TABLE",jp:"ブリュッセル・テーブル神楽坂",category:"World Beer Restaurant",area:"神楽坂",station:"飯田橋駅",walk:6,score:91,price:"¥¥¥",open:"17:00–23:00",closed:"水曜",tags:["Belgian","料理重視","古民家"],note:"ベルギーの修道院ビールと煮込み料理を静かな古民家で。",reason:"グラス管理と料理の完成度が高く、ペアリングで価値が増す一軒。",scores:[90,96,91,88],lat:35.7017,lng:139.7400 },
  { id:4,name:"WEST 9 BEER PUB",jp:"ウエストナイン・ビアパブ",category:"Beer Pub",area:"新宿",station:"新宿三丁目駅",walk:2,score:89,price:"¥¥",open:"16:00–24:00",closed:"無休",tags:["UK Pub","Cask Ale","駅近"],note:"ハンドポンプから注ぐ穏やかなエールと、短い会話を楽しむ街角。",reason:"カスクの状態管理と気取らない接客が魅力。遅い時間にも頼れる。",scores:[91,86,92,87],lat:35.6906,lng:139.7066 },
  { id:5,name:"MALT YARD ASAKUSA",jp:"モルトヤード浅草",category:"Brewery",area:"浅草",station:"浅草駅",walk:8,score:88,price:"¥¥",open:"13:00–21:00",closed:"木曜",tags:["Lager","屋上席","醸造所"],note:"すっきりしたラガーを軸に、下町の空が開ける屋上席へ。",reason:"低温発酵の丁寧さと飲み疲れない設計。観光の途中にも組み込みやすい。",scores:[91,85,89,87],lat:35.7148,lng:139.7967 },
  { id:6,name:"HOP STAND SHIBUYA",jp:"ホップスタンド渋谷",category:"Taproom",area:"渋谷",station:"渋谷駅",walk:7,score:87,price:"¥¥",open:"14:00–23:30",closed:"月曜",tags:["Hazy IPA","DJ","立ち飲み"],note:"香りの立つホップ系を少量から試せる、音楽好きのスタンド。",reason:"回転の速いタップと少量サイズが優秀。混雑時の落ち着きに課題。",scores:[90,82,88,87],lat:35.6595,lng:139.7005 },
  { id:7,name:"NORTH LINE ALEHOUSE",jp:"ノースライン・エールハウス",category:"Beer Pub",area:"上野",station:"上野広小路駅",walk:4,score:86,price:"¥¥",open:"15:00–23:00",closed:"日曜",tags:["Pale Ale","一人飲み","老舗"],note:"木のカウンターで定番エールを。選びやすい解説がうれしい。",reason:"定番を最高の状態で出す堅実さ。初心者にも通にも安心。",scores:[88,83,91,82],lat:35.7074,lng:139.7731 },
  { id:8,name:"BALTIC KITCHEN",jp:"バルティック・キッチン代々木",category:"World Beer Restaurant",area:"代々木",station:"代々木駅",walk:4,score:85,price:"¥¥¥",open:"17:30–23:00",closed:"火曜",tags:["北欧","Smoked","魚料理"],note:"北欧のスモーク料理に、酸味とハーブのあるビールを合わせる。",reason:"珍しい北欧系の品揃えと料理の相性。ビール単体の選択肢はやや少なめ。",scores:[84,93,82,81],lat:35.6831,lng:139.7020 },
  { id:9,name:"CANAL BREW LAB",jp:"キャナル・ブリューラボ天王洲",category:"Brewery",area:"天王洲",station:"天王洲アイル駅",walk:6,score:84,price:"¥¥",open:"11:30–22:00",closed:"不定休",tags:["実験醸造","Waterfront","Pilsner"],note:"運河沿いの開放的な醸造所で、小仕込みの実験作を比べる。",reason:"意欲的な小仕込みと昼からの使いやすさ。都心からの距離で僅かに減点。",scores:[87,84,83,82],lat:35.6220,lng:139.7497 },
  { id:10,name:"OLD MARKET BIERHALLE",jp:"オールドマーケット・ビアハレ",category:"World Beer Restaurant",area:"日本橋",station:"三越前駅",walk:2,score:83,price:"¥¥¥",open:"11:30–22:30",closed:"日曜",tags:["German","Lager","ソーセージ"],note:"正統派のドイツビールと料理を、歴史ある商店街の地下で。",reason:"クラシックスタイルの安心感と交通利便性。新奇性より完成度を評価。",scores:[85,89,83,75],lat:35.6860,lng:139.7745 },
];
const categories:(Category|"すべて")[]=["すべて","Brewery","Taproom","Beer Pub","World Beer Restaurant"];
const beers=["Kanda Table Saison","Riverbank West Coast IPA","Brussels Dubbel 8","Malt Yard Rice Lager","Canal Citrus Pilsner"];
const festivals=[
 {date:"10.03—04",month:"OCT",name:"TOKYO BAY CRAFT WEEKEND",jp:"東京ベイ・クラフトウィークエンド",place:"天王洲キャナルサイド",station:"天王洲アイル駅 徒歩6分",brewers:"28 BREWERS",style:"ラガー＆セゾン",ticket:"前売り受付中"},
 {date:"10.24—25",month:"OCT",name:"HOP HARVEST TOKYO",jp:"ホップ・ハーベスト東京",place:"上野恩賜公園 竹の台広場",station:"上野駅 徒歩4分",brewers:"42 BREWERS",style:"IPA＆フレッシュホップ",ticket:"9月20日発売"},
 {date:"11.07—08",month:"NOV",name:"BELGIAN TABLE DAYS",jp:"ベルジャン・テーブル・デイズ",place:"神楽坂セントラルプラザ",station:"飯田橋駅 徒歩2分",brewers:"16 IMPORTERS",style:"ベルギービール＆料理",ticket:"残席あり"},
];
const categoryLabel:Record<Category,string>={Brewery:"ブルワリー",Taproom:"タップルーム","Beer Pub":"ビアパブ","World Beer Restaurant":"世界のビール料理店"};

export default function Home(){
 const [tab,setTab]=useState<"explore"|"ranking"|"route"|"festivals">("explore"); const [category,setCategory]=useState<(typeof categories)[number]>("すべて"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Venue>(venues[0]); const [mapMode,setMapMode]=useState<"focus"|"all">("focus"); const [detailOpen,setDetailOpen]=useState(false); const [mobileMenu,setMobileMenu]=useState(false); const [duration,setDuration]=useState("半日"); const [stops,setStops]=useState("3軒"); const [focus,setFocus]=useState("バランスよく");
 const filtered=useMemo(()=>{const terms=query.trim().toLowerCase().split(/\s+/).filter(Boolean);return venues.filter(v=>{const haystack=[v.name,v.jp,v.area,v.station,v.category,categoryLabel[v.category],...v.tags,v.note,v.reason].join(" ").toLowerCase();return(category==="すべて"||v.category===category)&&terms.every(term=>haystack.includes(term))})},[category,query]);
 useEffect(()=>{if(filtered.length&&!filtered.some(v=>v.id===selected.id))setSelected(filtered[0])},[filtered,selected.id]);
 useEffect(()=>{setMapMode("focus")},[query,category]);
 const mapVenue=filtered.find(v=>v.id===selected.id)??filtered[0];
 const mapQuery=mapVenue?`${mapVenue.lat},${mapVenue.lng}`:"35.6812,139.7671";
 const mapUrl=mapMode==="all"?"https://www.google.com/maps?q=35.6812,139.7671&z=11&output=embed&hl=ja":`https://www.google.com/maps?q=${mapQuery}&z=${mapVenue?15:11}&output=embed&hl=ja`;
 const pointPositions:Record<number,[number,number]>={1:[53,38],2:[70,28],3:[38,35],4:[22,55],5:[79,19],6:[19,73],7:[62,22],8:[25,62],9:[52,79],10:[58,47]};
 const chooseVenue=(v:Venue)=>{setSelected(v);setDetailOpen(true)};
 useEffect(()=>{
  type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:Tool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined)}catch{/* Unsupported preview context. */}};
  register({name:"filter_beer_spots",title:"ビールスポットを絞り込む",description:"TOKYO BEER ATLASの店舗一覧を、キーワードと業態で絞り込み、検索画面を表示します。",inputSchema:{type:"object",properties:{query:{type:"string"},category:{type:"string",enum:categories}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const value=input as {query?:unknown;category?:unknown};if(value.query!==undefined&&typeof value.query!=="string")throw new Error("query must be a string");if(value.category!==undefined&&!categories.includes(value.category as (typeof categories)[number]))throw new Error("unknown category");setTab("explore");setQuery(typeof value.query==="string"?value.query:"");setCategory((value.category as (typeof categories)[number])??"すべて");return{section:"explore",query:typeof value.query==="string"?value.query:"",category:value.category??"すべて"}}});
  register({name:"show_beer_atlas_section",title:"セクションを表示",description:"検索、BEST 10、おすすめルート、ビアフェスのいずれかを表示します。",inputSchema:{type:"object",properties:{section:{type:"string",enum:["explore","ranking","route","festivals"]}},required:["section"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const section=(input as {section?:unknown}).section;if(!["explore","ranking","route","festivals"].includes(section as string))throw new Error("unknown section");setTab(section as typeof tab);return{section}}});
  return()=>lifecycle.abort();
 },[]);
 return <main><header className="site-header"><button className="brand" onClick={()=>setTab("explore")} aria-label="TOKYO BEER ATLAS ホーム"><span className="brand-mark"><Beer size={21}/></span><span><b>TOKYO BEER ATLAS</b><small>CRAFT BEER FIELD GUIDE</small></span></button><nav className="desktop-nav" aria-label="メインナビゲーション"><button className={tab==="explore"?"active":""} onClick={()=>setTab("explore")}>探す</button><button className={tab==="ranking"?"active":""} onClick={()=>setTab("ranking")}>BEST 10</button><button className={tab==="route"?"active":""} onClick={()=>setTab("route")}>おすすめルート</button><button className={tab==="festivals"?"active":""} onClick={()=>setTab("festivals")}>ビアフェス</button></nav><button className="menu-button" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="メニュー">{mobileMenu?<X/>:<Menu/>}</button>{mobileMenu&&<nav className="mobile-nav"><button onClick={()=>{setTab("explore");setMobileMenu(false)}}>探す</button><button onClick={()=>{setTab("ranking");setMobileMenu(false)}}>BEST 10</button><button onClick={()=>{setTab("route");setMobileMenu(false)}}>おすすめルート</button><button onClick={()=>{setTab("festivals");setMobileMenu(false)}}>ビアフェス</button></nav>}</header>
 {tab==="explore"&&<><section className="cover-strip"><Image src="/tokyo-beer-walk.png" alt="東京の川沿いでクラフトビール店を巡る版画調の街歩き" fill priority sizes="100vw"/><div className="cover-copy"><p>ISSUE 01 · TOKYO</p><h1>いい一杯を、<br/>街から探す。</h1><span>東京のブルワリーとビアパブを、味・空気・歩きやすさで選ぶ。</span></div></section>
 <section className="finder-shell" aria-label="店舗検索"><div className="finder-bar"><label className="search-box"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="エリア・店名・ビールスタイル"/></label><div className="area-chip"><MapPin size={17}/>東京23区</div><button className="route-shortcut" onClick={()=>setTab("route")}><Sparkles size={17}/>ルートをつくる</button></div><div className="category-row" aria-label="業態で絞り込む"><SlidersHorizontal size={17}/>{categories.map(item=><button key={item} onClick={()=>setCategory(item)} className={category===item?"selected":""}>{item==="すべて"?item:categoryLabel[item]}</button>)}</div></section>
 <section className="explore-grid"><div className={`map-panel ${mapMode==="all"?"all-points":""}`} aria-label="Google マップで見る東京クラフトビールマップ"><iframe className="google-map-frame" src={mapUrl} title={mapMode==="all"?"東京全域のGoogle マップ":mapVenue?`${mapVenue.jp}周辺のGoogle マップ`:"東京のGoogle マップ"} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>{mapMode==="all"&&venues.map(v=><button key={v.id} className={`overview-pin ${selected.id===v.id?"current":""}`} style={{left:`${pointPositions[v.id][0]}%`,top:`${pointPositions[v.id][1]}%`}} onClick={()=>setSelected(v)} aria-label={`${v.jp}を地図で選択`}><span>{v.id}</span></button>)}<div className="map-caption"><span>GOOGLE MAPS · {mapMode==="all"?venues.length:filtered.length} SPOTS</span>{mapMode==="all"?<><b>東京の全スポット</b><small><MapPin/>10地点を一度に表示</small></>:mapVenue?<><b>{mapVenue.jp}</b><small><MapPin/>{mapVenue.area} · {mapVenue.station}</small></>:<><b>該当するスポットがありません</b><small>検索条件を変えてください</small></>}<button className="map-mode-toggle" onClick={()=>setMapMode(mapMode==="all"?"focus":"all")}>{mapMode==="all"?"検索地点へ戻る":"全ポイントを表示"}</button><a href={`https://www.google.com/maps/search/?api=1&query=${mapMode==="all"?"craft beer Tokyo":mapQuery}`} target="_blank" rel="noreferrer">大きな地図で見る<ExternalLink/></a></div>{mapMode==="focus"&&filtered.length>1&&<div className="map-results" aria-label="地図に表示する店舗">{filtered.map(v=><button key={v.id} className={selected.id===v.id?"current":""} onClick={()=>setSelected(v)}><i>{v.id}</i><span>{v.area}</span></button>)}</div>}<div className="map-disclaimer">※ MVPの店舗・位置情報はサンプルです</div></div><div className="results-panel"><div className="section-kicker"><span>EDITOR&apos;S SELECTION</span><b>{filtered.length} SPOTS</b></div><h2>{query?`「${query}」の検索結果`:"いま、東京で飲むなら"}</h2><div className="venue-list">{filtered.map(v=><article key={v.id} className={`venue-row ${selected.id===v.id?"current":""}`} onMouseEnter={()=>setSelected(v)} onClick={()=>chooseVenue(v)}><div className="rank-no">{String(v.id).padStart(2,"0")}</div><div className="venue-main"><div className="venue-topline"><span>{categoryLabel[v.category]}</span><span>{v.area}</span></div><h3>{v.name}</h3><p>{v.jp}</p><div className="tag-line">{v.tags.slice(0,2).map(tag=><em key={tag}>#{tag}</em>)}</div></div><div className="venue-meta"><b>{v.score}</b><span>SCORE</span><small><Train size={13}/>{v.walk}分</small></div></article>)}{filtered.length===0&&<div className="empty-state"><Beer/><b>条件に合う店がありません</b><span>キーワードか業態を変えてみてください。</span></div>}</div></div></section></>}
 {tab==="ranking"&&<Ranking onSelect={chooseVenue}/>} {tab==="route"&&<RouteBuilder duration={duration} setDuration={setDuration} stops={stops} setStops={setStops} focus={focus} setFocus={setFocus} areaVenue={query.trim()?filtered[0]??null:null} onSelect={chooseVenue}/>} {tab==="festivals"&&<Festivals/>}<footer><div className="footer-mark"><Beer/> TOKYO BEER ATLAS</div><p>飲酒は20歳になってから。移動は徒歩・公共交通で。</p><span>MVP · SAMPLE DATA / 2026</span></footer>{detailOpen&&<VenueDetail venue={selected} onClose={()=>setDetailOpen(false)}/>}</main>
}

function Festivals(){return <section className="page-section festival-page"><div className="page-heading festival-heading"><p>BEER FESTIVAL CALENDAR · TOKYO</p><h1>街にひらく、<br/>ビールの祝祭。</h1><span>今季の注目フェスを、飲めるスタイルと街歩きのしやすさで選びました。</span></div><div className="festival-note"><b>2026 AUTUMN</b><span>掲載情報はMVP用サンプルです。実運用時は主催者の最新情報と連携します。</span></div><div className="festival-list">{festivals.map((festival,index)=><article className="festival-item" key={festival.name}><div className="festival-date"><small>{festival.month}</small><b>{festival.date}</b></div><div className="festival-copy"><span>0{index+1} · EDITOR&apos;S PICK</span><h2>{festival.name}</h2><p>{festival.jp}</p><div className="festival-facts"><em><MapPin/>{festival.place}</em><em><Train/>{festival.station}</em></div></div><div className="festival-side"><b>{festival.brewers}</b><span>{festival.style}</span><button>{festival.ticket}<ExternalLink/></button></div></article>)}</div><aside className="festival-tip"><Beer/><div><small>FIELD NOTE</small><b>フェスを気持ちよく楽しむために</b><p>最初に水を確保し、少量サイズを選びながら休憩を。会場へは公共交通で。</p></div></aside></section>}

function Ranking({onSelect}:{onSelect:(v:Venue)=>void}){const [mode,setMode]=useState("総合");return <section className="page-section ranking-page"><div className="page-heading"><p>THE TOKYO LIST · 2026</p><h1>東京のクラフトビール<br/>BEST 10</h1><span>味わい、独自性、接客、街との関係。4つの視点から編集部が選びました。</span></div><div className="mode-switch">{["総合","ブルワリー","料理と楽しむ","IPA好き"].map(item=><button key={item} className={mode===item?"active":""} onClick={()=>setMode(item)}>{item}</button>)}</div><div className="ranking-layout"><div className="ranking-list">{venues.map((v,i)=><button className="ranking-item" key={v.id} onClick={()=>onSelect(v)}><span className="big-rank">{String(i+1).padStart(2,"0")}</span><span className="ranking-name"><small>{categoryLabel[v.category]} · {v.area}</small><b>{v.name}</b><em>{v.jp}</em></span><span className="score-ring">{v.score}</span></button>)}</div><aside className="ranking-note"><span>HOW WE RATE</span><h2>順位のつくり方</h2><p>話題性だけに寄らず、一杯の品質とその場所で過ごす時間を同じ重さで見ています。</p>{["ビールの品質","サービス・知識","体験・空間","独自性"].map((item,i)=><div className="rating-key" key={item}><i>{i+1}</i><b>{item}</b><span>{[35,25,25,15][i]}%</span></div>)}<small>※ MVPでは編集用サンプルスコアを使用しています。</small></aside></div></section>}

function RouteBuilder({duration,setDuration,stops,setStops,focus,setFocus,areaVenue,onSelect}:{duration:string;setDuration:(v:string)=>void;stops:string;setStops:(v:string)=>void;focus:string;setFocus:(v:string)=>void;areaVenue:Venue|null;onSelect:(v:Venue)=>void}){
 const count=Number.parseInt(stops,10); const anchor=areaVenue; const origin=anchor??{lat:35.6812,lng:139.7671};
 const distance=(a:{lat:number;lng:number},b:{lat:number;lng:number})=>Math.hypot((a.lat-b.lat)*111,(a.lng-b.lng)*91);
 const focusBonus=(v:Venue)=>focus==="IPA中心"?(/ipa/i.test(`${v.tags.join(" ")} ${v.reason}`)?35:0):focus==="料理重視"?(v.category==="World Beer Restaurant"?35:0):focus==="醸造所優先"?(v.category==="Brewery"?35:0):0;
 const candidates=venues.filter(v=>v.id!==anchor?.id).sort((a,b)=>(focusBonus(b)+b.score-distance(origin,b)*1.7)-(focusBonus(a)+a.score-distance(origin,a)*1.7));
 const routeVenues=(anchor?[anchor,...candidates]:candidates).slice(0,count); const routeDistance=routeVenues.slice(1).reduce((sum,v,i)=>sum+distance(routeVenues[i],v),0).toFixed(1);
 const startMinutes=duration==="3時間"?17*60:duration==="1日"?11*60+30:14*60; const interval=duration==="3時間"?80:duration==="1日"?135:105; const timeAt=(i:number)=>{const value=startMinutes+i*interval;return`${String(Math.floor(value/60)%24).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`};
 const areaName=anchor?.area??"東京"; const routeTitle=focus==="IPA中心"?`${areaName}から巡る、ホップの香り旅`:focus==="料理重視"?`${areaName}から巡る、料理とビールの旅`:focus==="醸造所優先"?`${areaName}から巡る、できたて醸造所旅`:`${areaName}から巡る、東京ビール散歩`;
 const rationale=focus==="IPA中心"?"IPAの品揃えを最優先し、香りと苦味の違いを比べられる順番にしました。":focus==="料理重視"?"料理の評価が高い店を軸に、軽い一皿からしっかりしたペアリングへ進みます。":focus==="醸造所優先"?"醸造所併設店を優先し、できたての一杯と仕込みの個性を楽しめる構成です。":"ビールのスタイルが重なりすぎないよう、品質・移動距離・店の個性を均等に見ています。";
 const beerSets:Record<string,string[]>={"バランスよく":beers,"IPA中心":["Riverbank West Coast IPA","Hop Stand Hazy IPA","Kanda Session IPA","North Line English IPA","Canal Cold IPA"],"料理重視":["Kanda Table Saison","Brussels Dubbel 8","Baltic Smoked Ale","Malt Yard Rice Lager","Old Market Helles"],"醸造所優先":["Malt Yard Rice Lager","Kanda Table Saison","Canal Citrus Pilsner","Riverbank West Coast IPA","Canal Experimental Sour"]}; const routeBeers=beerSets[focus];
 return <section className="page-section route-page"><div className="page-heading route-heading"><p>BEER TRIP PLANNER</p><h1>今日は、どんな<br/>ビール旅にする？</h1><span>営業時間と移動時間を合わせて、無理なくおいしく巡れる順番を提案します。</span></div><div className="planner"><aside className="planner-controls">{anchor&&<div className="route-origin"><MapPin/><span><small>検索エリアを反映</small><b>{anchor.area}から出発</b></span></div>}<Choice label="時間" icon={<Clock3/>} values={["3時間","半日","1日"]} value={duration} onChange={setDuration}/><Choice label="軒数" icon={<MapPin/>} values={["2軒","3軒","4軒"]} value={stops} onChange={setStops}/><Choice label="こだわり" icon={<Star/>} values={["バランスよく","IPA中心","料理重視","醸造所優先"]} value={focus} onChange={setFocus}/><div className="transport-note"><Footprints/><div><b>徒歩＋公共交通で移動</b><span>飲酒を伴うため車移動は提案しません</span></div></div></aside><div className="itinerary"><div className="itinerary-head"><div><p>RECOMMENDED ROUTE · {focus}</p><h2>{routeTitle}</h2></div><span><b>{duration} · {stops}</b>約 {routeDistance}km</span></div><p className="route-rationale">{rationale}</p><div className="timeline">{routeVenues.map((v,i)=><div key={v.id}><button className="route-stop" onClick={()=>onSelect(v)}><span className="stop-time">{timeAt(i)}</span><span className="stop-number">{i+1}</span><span className="stop-copy"><small>{categoryLabel[v.category]} · {v.area}</small><b>{v.name}</b><em>ここで飲む：{routeBeers[i]}</em></span><span className="stop-score">{v.score}</span></button>{i<routeVenues.length-1&&<div className="travel-line"><ArrowDown/><Train/> 電車＋徒歩 約 {Math.max(12,Math.round(distance(v,routeVenues[i+1])*4))}分</div>}</div>)}</div><div className="five-beers"><div><Beer/><span><small>FOR THE WHOLE TRIP · {focus}</small><b>このルートで飲むべき5杯</b></span></div><ol>{routeBeers.map((beer,i)=><li key={beer}><i>{i+1}</i>{beer}</li>)}</ol></div></div></div></section>}

function Choice({label,icon,values,value,onChange}:{label:string;icon:React.ReactNode;values:string[];value:string;onChange:(v:string)=>void}){return <fieldset className="choice"><legend>{icon}{label}</legend><div>{values.map(item=><button type="button" key={item} className={value===item?"active":""} onClick={()=>onChange(item)}>{item}</button>)}</div></fieldset>}

function VenueDetail({venue,onClose}:{venue:Venue;onClose:()=>void}){const isRestaurant=venue.category==="World Beer Restaurant";return <div className="detail-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="detail-sheet" aria-modal="true" role="dialog" aria-label={`${venue.jp}の詳細`}><button className="detail-close" onClick={onClose} aria-label="閉じる"><X/></button><div className="detail-mast"><span>{categoryLabel[venue.category]} · {venue.area}</span><h2>{venue.name}</h2><p>{venue.jp}</p><div className="detail-score"><b>{venue.score}</b><small>EDITOR&apos;S SCORE</small></div></div><div className="detail-body"><p className="lead">{venue.note}</p><div className="quick-facts"><span><Clock3/><b>営業時間</b><em>{venue.open}</em></span><span><BookOpen/><b>定休日</b><em>{venue.closed}</em></span><span><Train/><b>最寄り</b><em>{venue.station} 徒歩{venue.walk}分</em></span></div><div className="detail-section"><p className="eyebrow">WHY IT RANKS</p><h3>この順位の理由</h3><p>{venue.reason}</p><div className="score-bars">{["品質","サービス","体験","独自性"].map((label,i)=><div key={label}><span>{label}</span><i><b style={{width:`${venue.scores[i]}%`}}/></i><em>{venue.scores[i]}</em></div>)}</div></div><div className="detail-section"><p className="eyebrow">MUST-TRY</p><h3>飲むべき3杯</h3><ol className="must-list"><li><i>1</i><span><b>House Table Saison</b><em>柑橘、白胡椒、ドライな余韻</em></span></li><li><i>2</i><span><b>Tokyo Pale Ale</b><em>松とグレープフルーツ、軽い苦味</em></span></li><li><i>3</i><span><b>Seasonal Small Batch</b><em>その日の限定仕込みをスタッフに</em></span></li></ol></div>{isRestaurant&&<div className="detail-section food-section"><p className="eyebrow">FOOD PAIRING</p><h3>食べるべき3品</h3><div className="food-grid"><span><Utensils/><b>牛頬肉のカルボナード</b><em>× Dubbel</em></span><span><Utensils/><b>ムール貝の白ビール蒸し</b><em>× Witbier</em></span><span><Utensils/><b>農家チーズの盛り合わせ</b><em>× Saison</em></span></div></div>}<div className="detail-section"><p className="eyebrow">VOICES</p><h3>レビューを読む</h3><blockquote>「ビールの説明が押しつけがましくなく、初めてでも選びやすい。平日の早い時間が心地よかった」</blockquote><p className="review-note">消費者レビュー要約 · サンプル</p></div><div className="links"><a href="#official" onClick={e=>e.preventDefault()}>公式サイト <ExternalLink/></a><a href="#article" onClick={e=>e.preventDefault()}>専門記事 <ExternalLink/></a><a href="#awards" onClick={e=>e.preventDefault()}><Award/>受賞歴を見る</a></div></div></aside></div>}
